/*
 * This source file was generated by the Gradle 'init' task
 */
package clase15;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        GestionVehiculo classUnderTest = new GestionVehiculo();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
