/*
 * This source file was generated by the Gradle 'init' task
 */
package clase15;

public class GestionVehiculo {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new GestionVehiculo().getGreeting());
    }
}
