/*
 * This source file was generated by the Gradle 'init' task
 */
package clase15;

import java.util.ArrayList;

import main.java.clase15.Sucursal;
import main.java.clase15.Vehiculo;
import main.java.clase15.VehiculoEstandar;

public class GestionVehiculo {

    public static void main(String[] args) {
        Sucursal bonitSucursal = new Sucursal("0","Sucursal Santiago Centro");
        VehiculoEstandar carrito = new VehiculoEstandar(null, null, 0);
    }
}
