/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER BDY1102_P1 IDENTIFIED BY "BDY1102_P1.practica_1"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P1 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P1;
GRANT "RESOURCE" TO BDY1102_P1;
ALTER USER BDY1102_P1 DEFAULT ROLE "RESOURCE";


/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER BDY1102_P1 IDENTIFIED BY "BDY1102_P1.practica_1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P1 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO BDY1102_P1;
GRANT "RESOURCE" TO BDY1102_P1;
ALTER USER BDY1102_P1 DEFAULT ROLE "RESOURCE";